---
title: "Project Proposal"
format: html
editor: visual
---

# Proposal

Your proposal should include:



-   A brief description of your dataset including its provenance, dimensions, etc. (Make sure to load the data and use inline code for some of this information.)


# Project Proposal

Dataset Description

- Our dataset, titled "Jobs and Salaries in Data Science," originates from [AI Jobs](https://ai-jobs.net/salaries/2023/). It encompasses various attributes crucial for understanding the landscape of data science careers. Below are key dimensions of our dataset:

Reasons for Dataset Selection

- As different career paths fall in and out of demand, it is hard to know what is a worth while pursuit in today's job market. We chose this data because we are all interested in careers in data science and we want be knowledgeable about the field as we prepare for graduation. 

Some Questions we are intested in Answering

Q1.  Relationship between Predictor Variables and Salary
   - Variables Involved: `job_title`, `experience_level`, `employment_type`, `work_setting`, `company_size`
   - Plan: We will analyze how various factors such as job title, experience level, employment type, work setting, and company size influence ones salary levels.

Q2. Job Title Breakdown by Demographic Factors
   - Variables Involved:`job_title`, `employee_residence`, `age`, `experience_level`, `work_setting`
   - Plan: See the differeince in the distribution of specific job titles across different variables like location, age, experience level, and work setting.

Q3. Extra question, Evolution of Data Science Jobs and Salaries Over Time
   - Variables Involved: `work_year`, `job_title`, `salary`
   - Plan: look at how the supply of data science jobs and  salaries have changed over time. Could Also be interesting to see  if there's a relationship between the average salary and the number of available jobs.



